### PR TITLE
keep old method signature for backwards compatibility

### PR DESCRIPTION
**Pull request by amitgilad3**
This should fix backward compatibility for RewriteDataFilesCommitManager

### CODE REVIEW

**Comment by amitgilad3** [comment]
Hey @zinking , i tried to make RewriteDataFilesCommitManager to be backwards compatible , please take a look and if its okay merge , tnx :)

**Comment by zinking** [comment]
you'd probably open another PR under apache iceberg

**Comment by amitgilad3** [comment]
if you prefer ill just open another pr so it wont bother you

**Comment by zinking** [comment]
I'm fine either way.

**Pull request merged**
